In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [3]:
data = pd.read_excel("Динамика СЭП РК 1991-2024 (англ).xls")
data.head(10)

,The main socio-economic indicators of the Republic of Kazakhstan,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Update date 05.08.2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
3,Socio-economic indicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Population at the end of the period (year),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,thousands of people,16451.7,16426.5,16334.9,15956.7,15675.8,15480.6,15188.2,14955.1,14901.6,...,17669.9,17918.2,18157.3,18395.6,18630.9,18879,19503.2,19766.8,20033.8,20283.4
6,as a percentage of the previous year,100.6,99.8,99.4,97.7,98.2,98.8,98.1,98.5,99.6,...,101.5,101.4,101.3,101.3,101.3,101.3,103.3,101.4,101.4,101.2
7,Life expectancy at birth of the population of ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,all population,67.6,67.4,65.4,64.9,63.5,63.6,64,64.5,65.63,...,71.97,72.41,72.95,73.15,73.39,71.51,70.38,74.45,75.1,75.44
9,men,62.6,62.4,60.1,59.7,58,58,58.4,59,60.6,...,67.49,67.99,68.72,68.84,69.22,67.36,66.64,70.27,70.99,71.33

In [4]:
data[4:]

,The main socio-economic indicators of the Republic of Kazakhstan,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
4,Population at the end of the period (year),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,thousands of people,16451.7,16426.5,16334.9,15956.7,15675.8,15480.6,15188.2,14955.1,14901.6,...,17669.9,17918.2,18157.3,18395.6,18630.9,18879,19503.2,19766.8,20033.8,20283.4
6,as a percentage of the previous year,100.6,99.8,99.4,97.7,98.2,98.8,98.1,98.5,99.6,...,101.5,101.4,101.3,101.3,101.3,101.3,103.3,101.4,101.4,101.2
7,Life expectancy at birth of the population of ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,all population,67.6,67.4,65.4,64.9,63.5,63.6,64,64.5,65.63,...,71.97,72.41,72.95,73.15,73.39,71.51,70.38,74.45,75.1,75.44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,17) The recalculation was carried out in accor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
285,18) In accordance with paragraph 2 of paragrap...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
286,"19) For 1990-2009, the data were compiled taki...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
288,20) Preliminary data.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN